name: ci.yml
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Run tests
        run: python -m pytest tests/ --maxfail=1 --disable-warnings -v